apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash.fullname" . }}-secrets
type: Opaque
stringData:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CASH_SERVICE_CLIENT_SECRET: "hbWy1ujh5VRYh185ECjGmOktu7TjJMoH"
