apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accounts.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "accounts.fullname" . }}
    app.kubernetes.io/component: backend
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}