apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounts.fullname" . }}-secrets
type: Opaque
stringData:
  DATABASE_PASSWORD:  "password"
  ACCOUNT_SERVICE_OAUTH2_CLIENT_SECRET: "fpbcLLRoXyEJolIXEfqMiRMsevqXZnXG"
