apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front-ui.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "front-ui.fullname" . }}
    app.kubernetes.io/component: frontend
data:
  SPRING_APPLICATION_NAME: {{ .Values.env.SPRING_APPLICATION_NAME | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: {{ .Values.env.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE: {{ .Values.env.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION_GRANT_TYPE: {{ .Values.env.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION_GRANT_TYPE | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_REDIRECT_URI: {{ .Values.env.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_REDIRECT_URI | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_PROVIDER: {{ .Values.env.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_PROVIDER | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: {{ .Values.env.SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI | quote }}
  SPRING_THYMELEAF_CACHE: {{ .Values.env.SPRING_THYMELEAF_CACHE | quote }}
  LOGGING_LEVEL_ROOT: {{ .Values.env.LOGGING_LEVEL_ROOT | quote }}
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: {{ .Values.env.LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY | quote }}
  GATEWAY_URL: {{ .Values.env.GATEWAY_URL | quote }}
