apiVersion: v1
kind: Secret
metadata:
  name: {{ include "front-ui.fullname" . }}-secrets
type: Opaque
stringData:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: "ui-client-secret"
