replicaCount: 1

image:
  repository: accounts-service
  pullPolicy: IfNotPresent
  tag: latest

env:
  DATABASE_HOST: bank-app-postgresql.default.svc.cluster.local
  DATABASE_PORT: 5432
  DATABASE_NAME: accounts
  DATABASE_USERNAME: postgres
#  DATABASE_PASSWORD: password
  KEYCLOAK_OAUTH2_URL: http://bank-app-keycloak.default.svc.cluster.local:8085/realms/bank-realm
  ACCOUNT_SERVICE_OAUTH2_CLIENT_ID: account-service
#  ACCOUNT_SERVICE_OAUTH2_CLIENT_SECRET: fpbcLLRoXyEJolIXEfqMiRMsevqXZnXG
#  SERVER_PORT: {{ .Values.service.port }}
  NOTIFICATION_SERVICE_URl: http://bank-app-notifications.default.svc.cluster.local:8086

secrets:
  DATABASE_PASSWORD: ""
  ACCOUNT_SERVICE_OAUTH2_CLIENT_SECRET: ""


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: true
  className: "nginx"
  annotations:
     kubernetes.io/ingress.class: nginx
  hosts:
    - host: bank.local
      paths:
        - path: /accounts
          pathType: Prefix
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
readinessProbe:
  httpGet:
    path: /actuator/health
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
