apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "transfer.fullname" . }}
    app.kubernetes.io/component: backend
data:
  SPRING_APPLICATION_NAME: {{ .Values.env.SPRING_APPLICATION_NAME | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.env.SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_TRANSFER_SERVICE_PROVIDER: {{ .Values.env.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_TRANSFER_SERVICE_PROVIDER | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_TRANSFER_SERVICE_CLIENT_ID: {{ .Values.env.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_TRANSFER_SERVICE_CLIENT_ID | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_TRANSFER_SERVICE_AUTHORIZATION_GRANT_TYPE: {{ .Values.env.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_TRANSFER_SERVICE_AUTHORIZATION_GRANT_TYPE | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: {{ .Values.env.SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI | quote }}
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: {{ .Values.env.MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE | quote }}
  BANK_ACCOUNTS_SERVICE_BASE_URL: {{ .Values.env.BANK_ACCOUNTS_SERVICE_BASE_URL }}
  LOGGING_LEVEL_ROOT: {{ .Values.env.LOGGING_LEVEL_ROOT | quote }}
  BOOTSTRAP_SERVERS: {{ .Values.env.BOOTSTRAP_SERVERS | quote }}