apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transfer.fullname" . }}-secret
type: Opaque
stringData:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: "xrBtLBR4QGuLpkOmCLBuL7qiUKkDDRhx"
