global:
  security:
    allowInsecureImages: true
  postgresql:
    auth:
      postgresPassword: password
      username: postgres
      password: password
      database: keycloak
    postgresqlPassword: password
    postgresqlUsername: postgres

kube-prometheus-stack:
  grafana:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.local
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      ruleSelector: {}

  prometheusOperator:
    enabled: true

zipkin:
  service:
    type: NodePort # По умолчанию ClusterIp
  ingress:
    enabled: true # По умолчанию выключен
    host: "zipkin.local"
    selfTracing:
      enabled: true  # По умолчанию выключено
  # Переопределяем использование ресурсов
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  # Включаем автоскейлинг
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3

kafka:
  ui:
    enabled: true
    service:
      type: ClusterIP
      port: 8087
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: kafka-ui.local


# PostgreSQL для Keycloak и accounts
postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: "latest"
  auth:
    existingSecret: postgres-password
    username: postgres
    database: keycloak
  primary:
    service:
      ports:
        postgresql: 5432

  initdb:
    scripts:
      create-accounts-db.sql: |
        CREATE DATABASE accounts;


keycloak:
  image:
    repository: docker.io/codecentric/keycloakx
    tag: latest
  service:
    type: ClusterIP
    ports:
      http: 8085
  postgresql:
    enabled: false
  externalDatabase:
    host: bank-app-postgresql.default.svc.cluster.local
    port: 5432
    database: keycloak
    user: postgres
    existingSecret: keycloak-db-secret
    existingSecretPasswordKey: password

  secret:
    create: true
    username: admin
    password: admin
#  extraEnv: |
#    - name: KC_DB
#      value: postgres
#    - name: KC_DB_URL
#      value: jdbc:postgresql://bank-app-postgresql:5432/keycloak
#    - name: KC_DB_USERNAME
#      value: postgres
#    - name: KC_DB_PASSWORD
#      value: password
#    - name: KC_HOSTNAME
#      value: keycloak.local
#    # realm import
#    - name: KEYCLOAK_IMPORT
#      value: /opt/keycloak/data/import/bank-realm.json

  extraVolumes: |
    - name: realm-config
      configMap:
        name: keycloak-realm

  extraVolumeMounts: |
    - name: realm-config
      mountPath: /opt/keycloak/data/import
      readOnly: true

accounts:
  enabled: true
  image:
    repository: accounts-service
    tag: "0.0.1-SNAPSHOT"
  service:
    port: 8081

cash:
  enabled: true
  image:
    repository: cash-service
    tag: "0.0.1-SNAPSHOT"
  service:
    port: 8084

front-ui:
  enabled: true
  image:
    repository: front-ui
    tag: "0.0.1-SNAPSHOT"
  service:
    port: 8080


notifications:
  enabled: true
  image:
    repository: notifications-service
    tag: "0.0.1-SNAPSHOT"
  service:
    port: 8086


transfer:
  enabled: true
  image:
    repository: transfer-service
    tag: "0.0.1-SNAPSHOT"
  service:
    port: 8083
