global:
  security:
    allowInsecureImages: true
  postgresql:
    auth:
      postgresPassword: password
      username: postgres
      password: password
      database: keycloak
    postgresqlPassword: password
    postgresqlUsername: postgres

########################################
# ELASTICSEARCH
########################################
elasticsearch:
  enabled: true
  imageTag: "8.12.0"
  replicas: 1
  minimumMasterNodes: 1
  resources:
    requests:
      cpu: "200m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "2Gi"
  protocol: http
  esConfig:
    elasticsearch.yml: |
      xpack.security.enabled: false
      discovery.type: single-node
  volumeClaimTemplate:
    storageClassName: "standard"
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: "2Gi"
  extraEnvs:
    - name: ES_JAVA_OPTS
      value: "-Xms1g -Xmx1g"

########################################
# LOGSTASH
########################################
logstash:
  enabled: true
  imageTag: "9.0.0"
  replicas: 1
  service:
    type: ClusterIP
    ports:
      - name: tcp
        port: 5044
        protocol: TCP
  logstashPipeline:
    logstash.conf: |
      input {
        tcp {
          port => 5044
          codec => json
        }
      }
      filter {
      
        if [password] {
          mutate {
            update => { "password" => "****" }
          }
        }
      
        grok {
          match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}" }
        }
      }
      
      output {
        elasticsearch {
          hosts => ["http://bank-app-elasticsearch-master.default.svc.cluster.local:9200"]
          ssl_enabled => false 
          ssl_verification_mode => "none"
          index => "bank-logs-%{+YYYY.MM.dd}"
        }
      stdout { codec => rubydebug }
      }

  extraEnvs:
    - name: LOG_LEVEL
      value: "debug"
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

########################################
# KIBANA
########################################
kibana:
  enabled: true
  imageTag: "8.12.0"
  replicas: 1
  elasticsearchHosts: "http://bank-app-elasticsearch-master.default.svc.cluster.local:9200"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - kibana.local
  elasticsearch:
    security:
      auth:
        enabled: false

########################################
# PROMETHEUS + GRAFANA
########################################
kube-prometheus-stack:
  enabled: true
  grafana:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.local
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      ruleSelector: {}
  prometheusOperator:
    enabled: true
  resources:
    requests:
      memory: 512Mi

########################################
# ZIPKIN
########################################
zipkin:
  enabled: true
  ingress:
    enabled: true
    host: "zipkin.local"
    selfTracing:
      enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
  extraEnv:
    - name: JAVA_OPTS
      value: "-Xms265m -Xmx256m -XX:+ExitOnOutOfMemoryError"
    - name: STORAGE_TYPE
      value: "elasticsearch"
    - name: ES_HOSTS
      value: "http://bank-app-elasticsearch-master.default.svc.cluster.local:9200"
    - name: ES_USERNAME
      value: "elastic"
    - name: ES_PASSWORD
      valueFrom:
          secretKeyRef:
          name: elasticsearch-master-credentials
          key: password

########################################
# KAFKA
########################################
kafka:
  enabled: true
  ui:
    enabled: true
    service:
      type: ClusterIP
      port: 8087
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: kafka-ui.local

########################################
# POSTGRESQL
########################################
postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: "latest"
  auth:
    existingSecret: postgres-password
    username: postgres
    database: keycloak
  primary:
    service:
      ports:
        postgresql: 5432
  initdb:
    scripts:
      create-accounts-db.sql: |
        CREATE DATABASE accounts;

########################################
# KEYCLOAK
########################################
keycloak:
  enabled: true
  image:
    repository: docker.io/codecentric/keycloakx
    tag: latest
  service:
    type: ClusterIP
    ports:
      http: 8085
  postgresql:
    enabled: false
  externalDatabase:
    host: bank-app-postgresql.default.svc.cluster.local
    port: 5432
    database: keycloak
    user: postgres
    existingSecret: keycloak-db-secret
    existingSecretPasswordKey: password
  secret:
    create: true
    username: admin
    password: admin
  extraVolumes: |
    - name: realm-config
      configMap:
        name: keycloak-realm
  extraVolumeMounts: |
    - name: realm-config
      mountPath: /opt/keycloak/data/import
      readOnly: true

########################################
# APPLICATION SERVICES
########################################
accounts:
  enabled: true
  image:
    repository: accounts-service
    tag: "0.0.1-SNAPSHOT"
  service:
    port: 8081

cash:
  enabled: true
  image:
    repository: cash-service
    tag: "0.0.1-SNAPSHOT"
  service:
    port: 8084

front-ui:
  enabled: true
  image:
    repository: front-ui
    tag: "0.0.1-SNAPSHOT"
  service:
    port: 8080

notifications:
  enabled: true
  image:
    repository: notifications-service
    tag: "0.0.1-SNAPSHOT"
  service:
    port: 8086

transfer:
  enabled: true
  image:
    repository: transfer-service
    tag: "0.0.1-SNAPSHOT"
  service:
    port: 8083
