spring:
  application:
    name: shared-kafka

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      client-id: "5L6g3nShT-eMCtK--X86sw"
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: "5L6g3nShT-eMCtK--X86sw"
      properties:
        spring.json.type.mapping: notificationRequest:yandex.workshop.api.model.NotificationRequest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
