spring:
  application:
    name: notifications-service

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KEYCLOAK_OAUTH2_URL:http://localhost:8085/realms/bank-realm}

      client:
        registration:
          notifications-service:
            provider: keycloak
            client-id: ${NOTIFICATION_SERVICE_OAUTH2_CLIENT_ID:notifications-service}
            client-secret: ${NOTIFICATION_SERVICE_OAUTH2_CLIENT_SECRET:S6Go9yKeRwksV47vydTv6R9izMSBFzJM}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_OAUTH2_URL":http://localhost:8085/realms/bank-realm}

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: notificationRequest:yandex.workshop.api.model.NotificationRequest
      group-id: bank-notifications
    listener:
      idle-partition-event-interval: 60000 # 60 секунд

topic:
  notification: notifications

server:
  port: ${SERVER_PORT:8086}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411//api/v2/spans}
  endpoint:
    prometheus:
      access: read_only
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    root: INFO
    org.springframework.webflux.function.server: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.core: DEBUG