apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notifications.fullname" . }}-secrets
type: Opaque
stringData:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: "S6Go9yKeRwksV47vydTv6R9izMSBFzJM"
