spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bank-ui
            client-secret: ui-client-secret
            scope: openid, profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: keycloak
        provider:
          keycloak:
#            issuer-uri: http://localhost:8085/realms/bank-realm
              authorization-uri: http://localhost:8085/realms/bank-realm/protocol/openid-connect/auth
              token-uri: http://localhost:8085/realms/bank-realm/protocol/openid-connect/token
              jwk-set-uri: http://localhost:8085/realms/bank-realm/protocol/openid-connect/certs
              user-info-uri: http://localhost:8085/realms/bank-realm/protocol/openid-connect/userinfo
              user-name-attribute: preferred_username
  thymeleaf:
    cache: false

gateway:
  url: http://api-gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: debug
    org.springframework.security: DEBUG