replicaCount: 1

image:
  repository: transfer-service
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8083

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: bank.local
      paths:
        - path: /transfer
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 250m
    memory: 512Mi

env:
  SPRING_APPLICATION_NAME: transfer-service
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://bank-app-keycloak.default.svc.cluster.local:8085/realms/bank-realm
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_TRANSFER_SERVICE_PROVIDER: keycloak
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_TRANSFER_SERVICE_CLIENT_ID: transfer-service
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_TRANSFER_SERVICE_AUTHORIZATION_GRANT_TYPE: client_credentials
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://bank-app-keycloak.default.svc.cluster.local:8085/realms/bank-realm
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
  BANK_ACCOUNTS_SERVICE_BASE_URL: http://bank-app-accounts.default.svc.cluster.local:8081
  LOGGING_LEVEL_ROOT: INFO
  BOOTSTRAP_SERVERS: bank-app-kafka-broker:9092

secrets:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: ""

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 120
readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 120

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


volumes: []
volumeMounts: []
nodeSelector: {}

tolerations: []

affinity: {}
