apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-elasticsearch-master-0-pv
  labels:
    app: elasticsearch-master
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/elasticsearch  # Путь на ноде
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - desktop-control-plane  # Ваша нода