elasticsearch:
  imageTag: "8.12.0"
  replicas: 1
  minimumMasterNodes: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  esConfig:
    elasticsearch.yml: |
      network.host: 0.0.0.0
      discovery.seed_hosts: elasticsearch-master-headless
      cluster.initial_master_nodes:
        - elasticsearch-master-0
      bootstrap.memory_lock: false
      xpack.security.enabled: false
#      xpack.security.transport.ssl.enabled: false
#      xpack.security.http.ssl.enabled: false
#      xpack.monitoring.enabled: false
#      xpack.monitoring.collection.enabled: true
#      xpack.ml.enabled: false
#      xpack.watcher.enabled: false
#
#  rbac:
#    create: false
#    serviceAccountAnnotations: {}
#  createCert: false

  volumeClaimTemplate:
    storageClassName: "standard"
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: "2Gi"
  extraEnvs:
    - name: ES_JAVA_OPTS
      value: "-Xms1g -Xmx1g"
  nodeSelector:
    kubernetes.io/hostname: desktop-control-plane
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
      operator: Exists

