input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {

   mutate {
      copy => { "[@metadata][kafka][topic]" => "source"}
    }

  if [password] {
    mutate {
      update => { "password" => "******" }
    }
  }

  if [account] {
    mutate {
      gsub => [
        "account", "\d{6,}", "******"
      ]
    }
  }

}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "bank-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }

}